### PR TITLE
Update to refer to slack chatroom

### LINKED ISSUE #57: Harvest Chat?
@bruth Is the HipChat Harvest chat still active? If not, I can strip out the references to it.

### PR DESCRIPTION
**Pull request by murphyke**
Fix #57.

I installed Jekyll and browsed and link-checked the results.

@bruth I don't know if you have control of the verbiage on http://harvest-platform.slack.com or http://harvest-platform.slack.com/signup, but if so, they could be made a little more inviting.

http://harvest-platform.slack.com mentions the pre-approved email domains but gives the impression that anybody else is out of luck. It should probably suggest sending email to the harvest info email address for people who will need invitations.

http://harvest-platform.slack.com/signup says "Contact your Team Administrator for an invitation" but doesn't say how to do that.

### CODE REVIEW

**Comment by bruth** [comment]
Thanks, this is great!

> I don't know if you have control of the verbiage [...]

I perused the admin settings and it does not appear to be. Also they only offer invitation only or by domain for signups, so I presume that is why they have that "contact the administrator" message.

**Comment by bruth** [comment]
Rather than removing the chat page, could you include most of what is in the `_includes/chatroom.md` snippet? Otherwise the `http://harvest.reserach.chop.edu/chat/` link will be broken.

**Comment by murphyke** [comment]
Good call; re-pushed.

**Comment by bruth** [comment]
Deployed: http://harvest.research.chop.edu/chat/ Thanks!

**Pull request merged**
