### PR TITLE
Using your data edit 4

### PR DESCRIPTION
**Pull request by gracecodes144**
Reopening after deployment to dev.

Changed two you're --> your.
Added ETL link to Wikipedia.
Added 'are' for sense-making in Disclaimer.

### CODE REVIEW

**Comment by mitalia** [comment]
In "Connect Harvest..." we should probably have a little blurb about what syncdb does. A person reading that might worry that it's going to stomp all over their database. I'd describe more about what it does, maybe 2 - 3 sentences and add a reassurance that it plays nice (not all web frameworks are as careful with their syncdb equivalents).

There are a bunch of places that reference specific objects in Harvest like DataConcepts and DataFields. Avocado's docs should have some sort of high level definition we can link to for more info, if not, we should probably add those. 

On one hand, I like laying all this out at a high-level, but on the other, I'm concerned because a novice user can read this but not actually _do_ any of it without a lot more detail that is promised in future posts. The intro says the details will be coming, but I still couldn't shake my expectation that there would be more "meat" in this specific post. I think changing the title to: First Steps to Using your data with Harvest. Perhaps in each section you could have a little "Homework assignment box" that calls out the things one should do as prerequisites for when that post arrives? You could then collect the links to the external docs and anything else in one place so that it's highly skimmable.

**Comment by gracecodes144** [comment]
In general, I chose to lay things out at a high level in an introductory post for several reasons:
1. Breaking the tutorial up into chunks will spread out the creation workload for me and you editors
2. Users who just need a little help and/or want to figure the details out for themselves anyway won't have to wait for the whole tutorial to be written
3. Users who need more help will probably have to wait about the same amount of time for full instruction, and can start doing "Homework" right away
4. It gets the conversation going
5. I wasn't sure that the style of tutorial I wanted to write would fit in the Docs section right away, so I wanted to start getting it out there and then possibly reformat or edit for a final resting place (content first)

Addressing @mitalia specific comments:
1. I think a short reassurance that syncdb won't touch preexisting data would be good, but I don't want to add a deeper description of function, as that violates my general thinking from above
2. I agree that Avocado's docs should have a high level definition of DataFields and DataConcepts, but I wasn't able to find them (I feel like they used to exist in the old documentation...or maybe I'm just going crazy)
3. I like the title change and Homework assignment box idea, I'll try to figure out a good way of implementing the second and post what I come up with

**Comment by mitalia** [comment]
Make no mistake, I was not being critical of the approach. I agree that small incremental steps are the only way this gets done, I was more saying that we needed to somehow set those expectations for anyone who reads this that that's what is going on. This is a _great_ beginning and is sorely needed.

**Comment by gracecodes144** [comment]
No mistake, I'm with you!
- Changed the title
- Added emphasis to outline and acknowledged that more info might be required
- Added reassurance about syncdb (also, this is the first info box on the django docs syncdb site)
- Added homework sections

Other thoughts: Looking it over again, I think the "Extras" section is a little out of place and might just add to the feeling that there is too much introduced without enough info to back it up. Maybe I should remove that section (and possible the Disclaimer section too) and replace with a summary or wrap-up. Feelings on that?

**Comment by gracecodes144** [comment]
Finally got back to this, just wrapped the article up with some contact links. (Removed the extras and disclaimer section as they felt extraneous.) It seemed to short for a summary, so I went with contact info (including the now-ACTIVE listserv).

**Comment by bruth** [comment]
The disclaimer is still there?

**Comment by gracecodes144** [comment]
git add -u would have helped :)

**Pull request merged**
